### ISSUE TITLE
cheahjs/palworld-save-tools convert.py has changed locations

### ISSUE THREAD

**Issue by sammcanany** [adefee/paver-palworld-save-editor#1]
The convert.py has been moved to palworld-save-tools-cheahjs\palworld_save_tools\commands. Constantly get error:
``` Unable to find "convert.py" locally ("./palworld-save-tools-cheahjs/convert.py"), cloning from https://github.com/cheahjs/palworld-save-tools.git...
Error: Error: Command failed: git clone https://github.com/cheahjs/palworld-save-tools.git ./palworld-save-tools-cheahjs
fatal: destination path './palworld-save-tools-cheahjs' already exists and is not an empty directory.

    at cloneGitRepo (C:\snapshot\palworld-save-editor\lib\cloneGitRepo.js)
    at async saveEditorMain (C:\snapshot\palworld-save-editor\index.js) 
```

Edit:
It seems that cloning the repository and the releases are different for cheahjs/palworld-save-tools/ so instead of having it clone the repository maybe it should download and extract the release.

**Comment by adefee** [comment]
It shouldn't try to clone if it finds the convert.py in that directory, so as a temporary workaround you could try copying convert.py there.

Thank you for flagging this - convert.py was previously in the main repo, and as you said appears to now only be available via releases. I'm working on a significant refactor right now, will include this change, too! <3
