### ISSUE TITLE
Cannot Load Level.sav

### ISSUE THREAD

**Issue by Cyconi** [adefee/paver-palworld-save-editor#2]
Using default config.json path of './config.json'. If you want to use a different path, use the '-c' flag
Found CheahJS' save-tools locally ("./palworld-save-tools-cheahjs/convert.py"), so conversion should be possible if necessary.
Checking for save files in C:\Users\jshil\AppData\Local\Pal\Saved\SaveGames\76561198362830626\2AA0C6CF4D0D6A5D2BCEB29BC60E18C8...
Found Label.sav, checking for existing converted JSON:
Label.sav has already been converted to JSON, so using that as base. If this is not desired, set "convertFreshEveryRun" to true in config.json, or remove the existing Label.sav.json file.
Error loading converted Label.sav into memory: Cannot create a string longer than 0x1fffffe8 characters
Found LabelMeta.sav, checking for existing converted JSON:
LabelMeta.sav has already been converted to JSON, so using that as base. If this is not desired, set "convertFreshEveryRun" to true in config.json, or remove the existing LabelMeta.sav.json file.
Loaded LabelMeta.sav into memory. You should see a magic value here: 1396790855
Exporting report as JSON...
exportPath was given without a .json extension, so we will treat it as a directory and use a timestamp.json filename.
Report written written to ./reports/pal-2024-02-04_020224.json

===========================
One or more errors were found during run: [
  'Error loading converted Label.sav into memory, see logs.',
  'In-memory Level.sav seems to be missing or incomplete. We use this to update world and player data, so we will not continue without it.'
]
===========================

===========================
Application has finished running
Press enter to exit..

**Comment by ExE-Boss** [comment]
Yeah, the size of `Level.sav.json` is too big for **V8**.

**Paver** needs to pass the `--minify-json` option to **palworld-save-tools** so that the generated **JSON** file is smaller.

**Comment by Cyconi** [comment]
So is there anything i can do?

**Comment by adefee** [comment]
Short-term, no, nothing for you to do - I have a major rewrite of Paver that I'm nearly done with, should completely remove that error and should work with any SAV filesize (even without the `--minify-json` option @ExE-Boss aptly mentioned).

The rewrite is largely working, but still a good bit of work/testing to do on it. Hoping to have it out tonight, but might be tomorrow evening after work. Would be happy to respond back here and/or tag you if you'd like. In the meantime, I'm also available (and lots of other helpful community members, too) in our Discord if you'd like to join: https://discord.gg/tu2rnEBWn9
