### ISSUE TITLE
Unable to find a player

### ISSUE THREAD

**Issue by Cyconi** [adefee/paver-palworld-save-editor#5]
it seems to not be able to find my own player save
![image](https://github.com/adefee/paver-palworld-save-editor/assets/94489327/0945d0bb-3d7f-4629-8ae6-7985c17bfa09)
![image](https://github.com/adefee/paver-palworld-save-editor/assets/94489327/8a42395e-ea70-4ba1-b5d9-d33f512f2395)

**Comment by adefee** [comment]
Was this a single player/coop-invite-code save? I haven't tested extensively with coops, but the latest release (2.0.10) should handle that better (just released few mins ago). Can you try that and see if you still get the same?

**Comment by Cyconi** [comment]
Its just a multiplayer join by code world

**Comment by Cyconi** [comment]
the lastest release seems to have the issue fixed tho
