### ISSUE TITLE
Directory does not exsist error?

### ISSUE THREAD

**Issue by InkDragon** [adefee/paver-palworld-save-editor#6]
pretty much what the title says, I believe I've correctly set the directory in the config, running paver from my d drive if that matters

![image](https://github.com/adefee/paver-palworld-save-editor/assets/3854603/05ec5a8c-8a5e-4ff0-a1cd-a0b6235b589d)
[pal-2024-02-09_094517-failed.json](https://github.com/adefee/paver-palworld-save-editor/files/14223073/pal-2024-02-09_094517-failed.json)

**Comment by adefee** [comment]
Your path is `C:\.....` but Paver appears to be looking for `<C:\.....`. Please check your config.json file and make sure you didn't enter a `<` before the path.

**Comment by adefee** [comment]
Please reopen this issue if you still get the error after checking your config file.
